import type { AnalysisResults, StageResult } from '@/types';

interface IdeaInfo {
  title: string;
  description: string;
  categories?: string[];
  sourceUrl?: string;
  score?: number;
}

const STAGE_TITLES = {
  market: '📊 Market Analysis (Анализ рынка)',
  demand: '🎯 Demand Analysis (Анализ спроса и болей)',
  communities: '👥 Communities (Сообщества и инфлюенсеры)',
  competition: '⚔️ Competitive Analysis (Конкурентный анализ)',
  forecast: '🔮 Market Forecast (Прогноз развития рынка)',
  gtm: '🚀 GTM Strategy (Go-to-Market стратегия)',
  tech: '⚙️ Technical Feasibility (Техническая реализуемость)',
  customers: '🧠 Customer Psychology (Психология клиентов)',
};

/**
 * Generate Markdown document from analysis results
 */
export function generateMarkdownReport(
  ideaInfo: IdeaInfo,
  analysisResults: AnalysisResults
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# 🚀 Business Idea Analysis: ${ideaInfo.title}\n`);
  lines.push(`**Generated:** ${new Date().toLocaleString('ru-RU')}\n`);
  lines.push('---\n');

  // Idea Information
  lines.push('## 💡 Idea Overview\n');
  lines.push(`**Title:** ${ideaInfo.title}\n`);
  lines.push(`**Description:** ${ideaInfo.description}\n`);

  if (ideaInfo.categories && ideaInfo.categories.length > 0) {
    lines.push(`**Categories:** ${ideaInfo.categories.join(', ')}\n`);
  }

  if (ideaInfo.sourceUrl) {
    lines.push(`**Source:** [${ideaInfo.sourceUrl}](${ideaInfo.sourceUrl})\n`);
  }

  if (ideaInfo.score) {
    lines.push(`**Score:** ${ideaInfo.score}\n`);
  }

  lines.push('\n---\n');

  // Table of Contents
  lines.push('## 📋 Table of Contents\n');
  const stageKeys = Object.keys(analysisResults) as (keyof AnalysisResults)[];
  stageKeys.forEach((key, index) => {
    const title = STAGE_TITLES[key] || key;
    lines.push(`${index + 1}. [${title}](#${key})\n`);
  });
  lines.push('\n---\n');

  // Executive Summary (Statistics)
  const totalSources = stageKeys.reduce((sum, key) => {
    return sum + (analysisResults[key]?.citations?.length || 0);
  }, 0);

  const totalQuestions = stageKeys.reduce((sum, key) => {
    return sum + (analysisResults[key]?.relatedQuestions?.length || 0);
  }, 0);

  lines.push('## 📊 Executive Summary\n');
  lines.push(`- **Total Stages Analyzed:** ${stageKeys.length}/8\n`);
  lines.push(`- **Total Sources:** ${totalSources}\n`);
  lines.push(`- **Related Questions:** ${totalQuestions}\n`);
  lines.push(`- **Analysis Completed:** ${new Date().toLocaleDateString('ru-RU')}\n`);
  lines.push('\n---\n');

  // Each Stage
  stageKeys.forEach((key, index) => {
    const stage = analysisResults[key];
    if (!stage) return;

    const title = STAGE_TITLES[key] || key;
    lines.push(`## ${title} {#${key}}\n`);
    lines.push(`**Stage ${index + 1} of 8**\n\n`);

    // Analysis Content
    lines.push('### Analysis\n');
    lines.push(stage.analysis);
    lines.push('\n\n');

    // Citations
    if (stage.citations && stage.citations.length > 0) {
      lines.push('### 📚 Sources\n');
      lines.push(`*${stage.citations.length} sources*\n\n`);
      stage.citations.forEach((citation, idx) => {
        lines.push(`${idx + 1}. [${citation}](${citation})\n`);
      });
      lines.push('\n');
    }

    // Related Questions
    if (stage.relatedQuestions && stage.relatedQuestions.length > 0) {
      lines.push('### 💭 Related Questions\n');
      stage.relatedQuestions.forEach((question) => {
        lines.push(`- ${question}\n`);
      });
      lines.push('\n');
    }

    // Timestamp
    if (stage.completedAt) {
      const date = new Date(stage.completedAt);
      lines.push(`*Completed: ${date.toLocaleString('ru-RU')}*\n`);
    }

    lines.push('\n---\n');
  });

  // Footer
  lines.push('\n## 📝 Notes\n');
  lines.push('This report was automatically generated by the AI Idea Analyzer.\n');
  lines.push('All analysis is focused on the US market.\n');
  lines.push('\n---\n');
  lines.push(`**Report End** | Generated: ${new Date().toISOString()}\n`);

  return lines.join('\n');
}

/**
 * Generate filename for export
 */
export function generateFilename(title: string, format: 'md' | 'pdf' = 'md'): string {
  // Sanitize title for filename
  const sanitized = title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .substring(0, 50);

  const timestamp = new Date().toISOString().split('T')[0];
  return `${sanitized}-analysis-${timestamp}.${format}`;
}
